version: '3.8'

services:
  opencode-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  # gRPC
      - "8081:8081"  # HTTP Gateway
    environment:
      - OPENCODE_DEBUG=true
      - GRPC_PORT=8080
      - HTTP_PORT=8081
    volumes:
      # Mount workspace for file operations
      - ./workspace:/workspace
    working_dir: /workspace
    restart: unless-stopped
