apiVersion: v1
kind: Namespace
metadata:
  name: opencode-sessions
  labels:
    app: opencode-orchestrator
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: opencode-orchestrator
  namespace: opencode-sessions
  labels:
    app: opencode-orchestrator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opencode-orchestrator
  template:
    metadata:
      labels:
        app: opencode-orchestrator
    spec:
      serviceAccountName: opencode-orchestrator
      containers:
      - name: orchestrator
        image: ghcr.io/denysvitali/opencode:latest
        command: ["./opencode", "orchestrator"]
        ports:
        - containerPort: 9090
          name: grpc
        - containerPort: 9091
          name: http
        env:
        - name: NAMESPACE
          value: "opencode-sessions"
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        readinessProbe:
          httpGet:
            path: /health
            port: 9091
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /health
            port: 9091
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: opencode-orchestrator
  namespace: opencode-sessions
  labels:
    app: opencode-orchestrator
spec:
  selector:
    app: opencode-orchestrator
  ports:
  - name: grpc
    port: 9090
    targetPort: 9090
  - name: http
    port: 9091
    targetPort: 9091
  type: ClusterIP
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: opencode-orchestrator
  namespace: opencode-sessions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: opencode-orchestrator
rules:
- apiGroups: [""]
  resources: ["pods", "persistentvolumeclaims", "services"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: [""]
  resources: ["namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: opencode-orchestrator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: opencode-orchestrator
subjects:
- kind: ServiceAccount
  name: opencode-orchestrator
  namespace: opencode-sessions
